"""
Predictive alert and maintenance models for Project AEGIS.

This module contains data structures for failure predictions and maintenance recommendations.
"""

import uuid
from datetime import datetime
from typing import Any

from pydantic import BaseModel, Field

from .enums import AlertSeverity, FailureCategory, MaintenanceUrgency


class PredictiveAlert(BaseModel):
    """Alert generated by ML model or rule-based engine."""

    alert_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()), description="Unique alert identifier"
    )
    vehicle_id: str
    timestamp: datetime
    severity: AlertSeverity
    category: FailureCategory

    component: str = Field(
        ...,
        description="Specific component (e.g., 'alternator', 'front_left_brake_pad')",
    )
    failure_probability: float = Field(
        ..., ge=0, le=1, description="Probability of failure (0.0-1.0)"
    )
    confidence: float = Field(
        ..., ge=0, le=1, description="Model confidence score (0.0-1.0)"
    )

    # Prediction Time Window
    predicted_failure_min_hours: float = Field(
        ..., ge=0, description="Minimum hours until failure"
    )
    predicted_failure_max_hours: float = Field(
        ..., ge=0, description="Maximum hours until failure"
    )
    predicted_failure_likely_hours: float = Field(
        ..., ge=0, description="Most likely hours until failure"
    )

    # Actionable Information
    can_complete_current_mission: bool = Field(
        ..., description="Safe to complete current mission"
    )
    recommended_action: str = Field(
        ..., description="Human-readable recommended action"
    )
    safe_to_operate: bool = Field(..., description="Vehicle safe for operation")

    # Context & Metadata
    contributing_factors: list[str] = Field(
        default_factory=list, description="List of contributing telemetry anomalies"
    )
    related_telemetry: dict[str, Any] = Field(
        default_factory=dict, description="Snapshot of relevant telemetry values"
    )
    model_version: str = Field(
        default="1.0.0", description="ML model version that generated alert"
    )

    # Orchestrator Response
    acknowledged: bool = Field(
        default=False, description="Alert acknowledged by orchestrator"
    )
    acknowledged_by: str | None = Field(
        None, description="User/system that acknowledged"
    )
    acknowledged_at: datetime | None = Field(
        None, description="Timestamp of acknowledgment"
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "alert_id": "alert-550e8400-e29b-41d4-a716-446655440000",
                "vehicle_id": "AMB-001",
                "timestamp": "2026-02-10T14:32:15.000Z",
                "severity": "warning",
                "category": "electrical",
                "component": "alternator",
                "failure_probability": 0.75,
                "confidence": 0.88,
                "predicted_failure_min_hours": 8.0,
                "predicted_failure_max_hours": 24.0,
                "predicted_failure_likely_hours": 12.0,
                "can_complete_current_mission": True,
                "safe_to_operate": True,
                "recommended_action": "Schedule alternator inspection within 12 hours",
                "contributing_factors": [
                    "battery_voltage declining trend",
                    "alternator_voltage below 13.5V",
                    "increased electrical load",
                ],
                "model_version": "1.0.0",
            }
        }
    }


class MaintenanceRecommendation(BaseModel):
    """Actionable maintenance advice generated from alerts."""

    recommendation_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique recommendation identifier",
    )
    vehicle_id: str
    timestamp: datetime
    urgency: MaintenanceUrgency

    component: str = Field(..., description="Component requiring maintenance")
    issue_description: str = Field(..., description="Detailed issue description")
    recommended_action: str = Field(..., description="Recommended maintenance action")

    # Resource Estimates
    estimated_downtime_hours: float = Field(
        ..., ge=0, description="Expected vehicle downtime"
    )
    parts_needed: list[str] = Field(
        default_factory=list, description="Required replacement parts"
    )
    estimated_labor_hours: float = Field(..., ge=0, description="Estimated labor time")
    estimated_cost_usd: float | None = Field(
        None, ge=0, description="Estimated cost in USD"
    )

    # Deferral Options
    can_defer: bool = Field(..., description="Whether maintenance can be postponed")
    deferral_risk: str | None = Field(
        None, description="Risk description if maintenance is deferred"
    )

    model_config = {
        "json_schema_extra": {
            "example": {
                "recommendation_id": "rec-550e8400-e29b-41d4-a716-446655440000",
                "vehicle_id": "AMB-001",
                "timestamp": "2026-02-10T14:32:20.000Z",
                "urgency": "urgent",
                "component": "alternator",
                "issue_description": "Alternator output voltage declining, bearing wear detected",
                "recommended_action": "Replace alternator assembly",
                "estimated_downtime_hours": 2.5,
                "parts_needed": ["Alternator Assembly 14V 200A", "Serpentine Belt"],
                "estimated_labor_hours": 2.0,
                "estimated_cost_usd": 450.00,
                "can_defer": True,
                "deferral_risk": "Risk of complete electrical failure within 24 hours",
            }
        }
    }
