"""
Predictive alert models for Project AEGIS.

This module contains data structures for failure predictions.
"""

import uuid
from datetime import datetime

from pydantic import BaseModel, Field

from .enums import AlertSeverity, FailureCategory


class PredictiveAlert(BaseModel):
    """Alert generated by ML model or rule-based engine."""

    alert_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()), description="Unique alert identifier"
    )
    vehicle_id: str
    timestamp: datetime
    severity: AlertSeverity
    category: FailureCategory

    component: str = Field(..., description="Specific component (e.g., 'engine_temp')")
    failure_probability: float = Field(
        ..., ge=0, le=1, description="Probability of failure (0.0-1.0)"
    )

    recommended_action: str = Field(..., description="Human-readable recommended action")

    # Metadata
    acknowledged: bool = Field(default=False, description="Alert acknowledged")

    model_config = {
        "json_schema_extra": {
            "example": {
                "alert_id": "alert-550e8400-e29b-41d4-a716-446655440000",
                "vehicle_id": "AMB-001",
                "timestamp": "2026-02-10T14:32:15.000Z",
                "severity": "warning",
                "category": "engine",
                "component": "engine_temp",
                "failure_probability": 0.85,
                "recommended_action": "Schedule immediate engine inspection",
            }
        }
    }
